//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailSharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailSharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineSchool.Contract.Resources.EmailSharedResources", typeof(EmailSharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao studentName&lt;br/&gt; Non sei riuscito ad acquistare il courseName soggetto..
        /// </summary>
        public static string BuyCourseError {
            get {
                return ResourceManager.GetString("BuyCourseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao studentName &lt;br/&gt; Hai acquistato con successo il courseName corso al prezzo di coursePrice € . &lt;br/&gt; La tua prima lezione inizierà alla data startDate.
        /// </summary>
        public static string BuyCourseSuccess {
            get {
                return ResourceManager.GetString("BuyCourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao name. Controlla il calendario allegato con i dettagli della riunione per programmare la tua riunione..
        /// </summary>
        public static string CalendarEmail {
            get {
                return ResourceManager.GetString("CalendarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma il tuo email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma il tuo account &lt;a href= HtmlEncoder&gt; cliccando qui&lt;/a&gt;..
        /// </summary>
        public static string ConfirmEmailLink {
            get {
                return ResourceManager.GetString("ConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utente con i seguenti dettagli richiede informazioni: &lt;br/&gt; Nome: fullName &lt;br/&gt; Email: email&lt;br/&gt; Message: message ..
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao user&lt;br/&gt; Ti stiamo inviando questa email solo per ricordarti che entro 3 ore puoi unirti alla meeting: topic  &lt;a href= https://meetingLink&gt;cliccando  qui&lt;/a&gt;..
        /// </summary>
        public static string MeetingEmailMessage {
            get {
                return ResourceManager.GetString("MeetingEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlineSchool Promemoria riunione.
        /// </summary>
        public static string MeetingEmailsubject {
            get {
                return ResourceManager.GetString("MeetingEmailsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online School Conferma di pagamento.
        /// </summary>
        public static string PaymentConfirmation {
            get {
                return ResourceManager.GetString("PaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetta la password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimposta la password facendo clic qui: &lt;a href=HtmlEncoder&gt;Reimposta Password&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordEmail {
            get {
                return ResourceManager.GetString("ResetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente creato con successo. Controlla la tua email per la verifica..
        /// </summary>
        public static string UserCreationSucces {
            get {
                return ResourceManager.GetString("UserCreationSucces", resourceCulture);
            }
        }
    }
}
