//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineSchool.Contract.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi siamo.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token di Accesso.
        /// </summary>
        public static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azioni.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi file.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi sessione.
        /// </summary>
        public static string AddSession {
            get {
                return ResourceManager.GetString("AddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi social.
        /// </summary>
        public static string AddSocial {
            get {
                return ResourceManager.GetString("AddSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutti i diritti riservati.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consenti sempre di partecipare?.
        /// </summary>
        public static string AlwaysAllowToJoin {
            get {
                return ResourceManager.GetString("AlwaysAllowToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei già un membro?.
        /// </summary>
        public static string AreYouAlreadyMember {
            get {
                return ResourceManager.GetString("AreYouAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai ancora un account?.
        /// </summary>
        public static string AreYouNotMember {
            get {
                return ResourceManager.GetString("AreYouNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assegna nuovo insegnante.
        /// </summary>
        public static string AssignNewTeacher {
            get {
                return ResourceManager.GetString("AssignNewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posti disponibili.
        /// </summary>
        public static string AvailableSpots {
            get {
                return ResourceManager.GetString("AvailableSpots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenota un corso.
        /// </summary>
        public static string BookCourse {
            get {
                return ResourceManager.GetString("BookCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprato.
        /// </summary>
        public static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquista ora.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllare il programma.
        /// </summary>
        public static string CheckProgram {
            get {
                return ResourceManager.GetString("CheckProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudere.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colore.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confrontare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inviaci un messaggio e ti contatteremo.
        /// </summary>
        public static string ContactFormHint {
            get {
                return ResourceManager.GetString("ContactFormHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contattaci.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corso creato con successo.
        /// </summary>
        public static string CourseCreateSuccess {
            get {
                return ResourceManager.GetString("CourseCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsi.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corso aggiornato con successo.
        /// </summary>
        public static string CourseUpdateSuccess {
            get {
                return ResourceManager.GetString("CourseUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di carta di credito.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clienti.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC numero.
        /// </summary>
        public static string CVCNumber {
            get {
                return ResourceManager.GetString("CVCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorni.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorni Fino alla Scadenza.
        /// </summary>
        public static string DaysUntilExpiration {
            get {
                return ResourceManager.GetString("DaysUntilExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina social.
        /// </summary>
        public static string DeleteSocial {
            get {
                return ResourceManager.GetString("DeleteSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli per soggetto.
        /// </summary>
        public static string DetailsForSubject {
            get {
                return ResourceManager.GetString("DetailsForSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenti.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica selezionato.
        /// </summary>
        public static string DownloadSelected {
            get {
                return ResourceManager.GetString("DownloadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna Corsi.
        /// </summary>
        public static string EditCourse {
            get {
                return ResourceManager.GetString("EditCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica social.
        /// </summary>
        public static string EditSocial {
            get {
                return ResourceManager.GetString("EditSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna studente.
        /// </summary>
        public static string EditStudent {
            get {
                return ResourceManager.GetString("EditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna soggetto.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna professore.
        /// </summary>
        public static string EditTeacher {
            get {
                return ResourceManager.GetString("EditTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inviata  con successo.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di fine.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo scaduto.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogni.
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scadenza.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femmina.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome del file.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensione del file .
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di file.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compila il form per acquistare il.
        /// </summary>
        public static string FillPaymentForm {
            get {
                return ResourceManager.GetString("FillPaymentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finito.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password dimenticata.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRATIS.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome / Congome.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genere.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attraverso lo studio della Bibbia potrai prepararti per servire meglio nella tua chiesa, comunità o nel campo della missione.
        /// </summary>
        public static string HeaderSmallTitle {
            get {
                return ResourceManager.GetString("HeaderSmallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I nostri corsi si rivolgono a coloro che desiderano conoscere di più Dio....
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora(e).
        /// </summary>
        public static string Hour_s_ {
            get {
                return ResourceManager.GetString("Hour(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In corso.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È ricorsivo?.
        /// </summary>
        public static string IsRecursive {
            get {
                return ResourceManager.GetString("IsRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aderire.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corso iscritto con successo. I pianificatori del calendario sono stati inviati al tuo indirizzo e-mail per ogni sessione..
        /// </summary>
        public static string JoinCourseSuccess {
            get {
                return ResourceManager.GetString("JoinCourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partecipata.
        /// </summary>
        public static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riunione partecipata con successo.Un programma di pianificazione del calendario è stato inviato al tuo indirizzo e-mail.
        /// </summary>
        public static string JoinMeetingSuccess {
            get {
                return ResourceManager.GetString("JoinMeetingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conoscimi.
        /// </summary>
        public static string Know_Me {
            get {
                return ResourceManager.GetString("Know Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo di lezione.
        /// </summary>
        public static string Lesson_Time {
            get {
                return ResourceManager.GetString("Lesson Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lezioni.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento dal vivo.
        /// </summary>
        public static string LiveEvent {
            get {
                return ResourceManager.GetString("LiveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accedere.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschio.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestire.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insegnante dirigente.
        /// </summary>
        public static string ManagingTeacher {
            get {
                return ResourceManager.GetString("ManagingTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiali.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incontro creato con successo.
        /// </summary>
        public static string MeetingCreateSuccessful {
            get {
                return ResourceManager.GetString("MeetingCreateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La riunione non è ancora pronta per iniziare..
        /// </summary>
        public static string MeetingNotReady {
            get {
                return ResourceManager.GetString("MeetingNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incontri.
        /// </summary>
        public static string Meetings {
            get {
                return ResourceManager.GetString("Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;incontro inizia tra.
        /// </summary>
        public static string MeetingStartsIn {
            get {
                return ResourceManager.GetString("MeetingStartsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolo della riunione.
        /// </summary>
        public static string MeetingTitle {
            get {
                return ResourceManager.GetString("MeetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incontro modificato con successo.
        /// </summary>
        public static string MeetingUpdateSuccessful {
            get {
                return ResourceManager.GetString("MeetingUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaggio.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuti.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miei Corsi.
        /// </summary>
        public static string MyCourses {
            get {
                return ResourceManager.GetString("MyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I miei incontri.
        /// </summary>
        public static string MyMeetings {
            get {
                return ResourceManager.GetString("MyMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I miei soggetti.
        /// </summary>
        public static string MySubjects {
            get {
                return ResourceManager.GetString("MySubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo corso.
        /// </summary>
        public static string NewCourse {
            get {
                return ResourceManager.GetString("NewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo documento.
        /// </summary>
        public static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova lezione.
        /// </summary>
        public static string NewLesson {
            get {
                return ResourceManager.GetString("NewLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo materiale.
        /// </summary>
        public static string NewMaterial {
            get {
                return ResourceManager.GetString("NewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo incontro.
        /// </summary>
        public static string NewMeeting {
            get {
                return ResourceManager.GetString("NewMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova sessione.
        /// </summary>
        public static string NewSession {
            get {
                return ResourceManager.GetString("NewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo social.
        /// </summary>
        public static string NewSocial {
            get {
                return ResourceManager.GetString("NewSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo studente.
        /// </summary>
        public static string NewStudent {
            get {
                return ResourceManager.GetString("NewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo documento dello studente.
        /// </summary>
        public static string NewStudentDocument {
            get {
                return ResourceManager.GetString("NewStudentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo soggetto.
        /// </summary>
        public static string NewSubject {
            get {
                return ResourceManager.GetString("NewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvo insegnante.
        /// </summary>
        public static string NewTeacher {
            get {
                return ResourceManager.GetString("NewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo documento dell&apos;insegnante.
        /// </summary>
        public static string NewTeacherDocument {
            get {
                return ResourceManager.GetString("NewTeacherDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova soggetto insegnante.
        /// </summary>
        public static string NewTeacherSubject {
            get {
                return ResourceManager.GetString("NewTeacherSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La prossima sessione inizia tra.
        /// </summary>
        public static string NextSession {
            get {
                return ResourceManager.GetString("NextSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun incontro disponibile al momento.
        /// </summary>
        public static string NoMeetingsAvailable {
            get {
                return ResourceManager.GetString("NoMeetingsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna risorsa caricata.
        /// </summary>
        public static string NoResourcesUploaded {
            get {
                return ResourceManager.GetString("NoResourcesUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun social network.
        /// </summary>
        public static string NoSocialNetworks {
            get {
                return ResourceManager.GetString("NoSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun insegnante assegnato.
        /// </summary>
        public static string NoTeachersAssigned {
            get {
                return ResourceManager.GetString("NoTeachersAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non pubblicato.
        /// </summary>
        public static string NotPublished {
            get {
                return ResourceManager.GetString("NotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non pubblicato (data di scadenza superata).
        /// </summary>
        public static string NotPublishedPassedDueDate {
            get {
                return ResourceManager.GetString("NotPublishedPassedDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna sessione in programma.
        /// </summary>
        public static string NoUpcomingSessions {
            get {
                return ResourceManager.GetString("NoUpcomingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I nostri corsi.
        /// </summary>
        public static string Our_Courses {
            get {
                return ResourceManager.GetString("Our Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I nostri social.
        /// </summary>
        public static string OUR_SOCIAL {
            get {
                return ResourceManager.GetString("OUR SOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I nostri relatori.
        /// </summary>
        public static string Our_Teachers {
            get {
                return ResourceManager.GetString("Our Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimpostazione della password riuscita.
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento non andato a buon fine!.
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento completato con successo. I pianificatori del calendario sono stati inviati al tuo indirizzo e-mail per ogni sessione..
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a testa.
        /// </summary>
        public static string PerPerson {
            get {
                return ResourceManager.GetString("PerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezzo.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il programma.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pubblicare.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pubblicato.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricaricare.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrati.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricordati di me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricordare la password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A distanza.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetta la password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risorse.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruoli.
        /// </summary>
        public static string ROLES {
            get {
                return ResourceManager.GetString("ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Righe disponibili.
        /// </summary>
        public static string RowsAvailable {
            get {
                return ResourceManager.GetString("RowsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orari.
        /// </summary>
        public static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca ora.
        /// </summary>
        public static string Search_Now {
            get {
                return ResourceManager.GetString("Search Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondi.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedi tutto.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona insegnante responsabile.
        /// </summary>
        public static string SelectManagingTeacher {
            get {
                return ResourceManager.GetString("SelectManagingTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona SocialNetwork.
        /// </summary>
        public static string SelectSocialNetwork {
            get {
                return ResourceManager.GetString("SelectSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona studente.
        /// </summary>
        public static string SelectStudent {
            get {
                return ResourceManager.GetString("SelectStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona insegnante.
        /// </summary>
        public static string SelectTeacher {
            get {
                return ResourceManager.GetString("SelectTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siamo prima di ogni cosa dei credenti salvati per grazia da Cristo Gesù. Crediamo nel simbolo Niceno Costantinopolitano (Padre, Figlio, Spirito Santo), nella nuova nascita, nel battesimo nello Spirito Santo e nei suoi doni. Crediamo nelle Sacre Scritture come unica via divina da seguire.
        /// </summary>
        public static string Service1_quote {
            get {
                return ResourceManager.GetString("Service1_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Siamo.
        /// </summary>
        public static string Service1_title {
            get {
                return ResourceManager.GetString("Service1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tratta di pastori e missionari che hanno dedicato la loro vita a servire Dio. Attraverso lo studio approfondito della parola, la preghiera, la meditazione e l&apos;esperienza sul campo hanno ideato i corsi che potrai seguire su questa piattaforma.
        /// </summary>
        public static string Service2_quote {
            get {
                return ResourceManager.GetString("Service2_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I nostri relatori.
        /// </summary>
        public static string Service2_title {
            get {
                return ResourceManager.GetString("Service2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senti un forte desiderio di servire di più il Signore? Vuoi approfondire maggiormente le tue conoscenze bibliche per un più efficace servizio nel ministero? Cosa aspetti, iscriviti ai nostri corsi!.
        /// </summary>
        public static string Service3_quote {
            get {
                return ResourceManager.GetString("Service3_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unisciti a noi.
        /// </summary>
        public static string Service3_title {
            get {
                return ResourceManager.GetString("Service3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessione.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessioni.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di social media.
        /// </summary>
        public static string SocialMediaType {
            get {
                return ResourceManager.GetString("SocialMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo sociale.
        /// </summary>
        public static string SocialType {
            get {
                return ResourceManager.GetString("SocialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venduto.
        /// </summary>
        public static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posti Disponibili.
        /// </summary>
        public static string SpotsAvailable {
            get {
                return ResourceManager.GetString("SpotsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cominciare.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data d&apos;inizio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora di inizio.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studente.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studente creato con successo.
        /// </summary>
        public static string StudentCreateSuccessful {
            get {
                return ResourceManager.GetString("StudentCreateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenti degli studenti.
        /// </summary>
        public static string StudentDocuments {
            get {
                return ResourceManager.GetString("StudentDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studente modificato con successo.
        /// </summary>
        public static string StudentEditSuccessful {
            get {
                return ResourceManager.GetString("StudentEditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soggetto.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soggetto creato con successo.
        /// </summary>
        public static string SubjectCreateSuccess {
            get {
                return ResourceManager.GetString("SubjectCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soggetto.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soggetto aggiornato con successo.
        /// </summary>
        public static string SubjectUpdateSuccess {
            get {
                return ResourceManager.GetString("SubjectUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inviare pagamento.
        /// </summary>
        public static string SubmitPayment {
            get {
                return ResourceManager.GetString("SubmitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insegnante.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiali per l&apos;insegnante.
        /// </summary>
        public static string Teacher_Materials {
            get {
                return ResourceManager.GetString("Teacher Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soggetto insegnante.
        /// </summary>
        public static string Teacher_Subject {
            get {
                return ResourceManager.GetString("Teacher Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insegnante creato con successo.
        /// </summary>
        public static string TeacherCreateSuccessful {
            get {
                return ResourceManager.GetString("TeacherCreateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenti degli insegnanti.
        /// </summary>
        public static string TeacherDocuments {
            get {
                return ResourceManager.GetString("TeacherDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insegnante modificato con successo.
        /// </summary>
        public static string TeacherEditSuccessful {
            get {
                return ResourceManager.GetString("TeacherEditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatori.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grazie per aver confermato la tua email.
        /// </summary>
        public static string ThankYouForConfirmingEmail {
            get {
                return ResourceManager.GetString("ThankYouForConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non pubblicato.
        /// </summary>
        public static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prossime Sessioni.
        /// </summary>
        public static string UpcomingSessions {
            get {
                return ResourceManager.GetString("UpcomingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebexIntegrazione.
        /// </summary>
        public static string WebexIntegration {
            get {
                return ResourceManager.GetString("WebexIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anni di esperienza.
        /// </summary>
        public static string YearsOfExperience {
            get {
                return ResourceManager.GetString("YearsOfExperience", resourceCulture);
            }
        }
    }
}
