//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationSharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationSharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineSchool.Contract.Resources.ValidationSharedResources", typeof(ValidationSharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il numero della tua carta è incompleto..
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore. Controlla il tuo indirizzo email e riprova..
        /// </summary>
        public static string CheckEmailError {
            get {
                return ResourceManager.GetString("CheckEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il colore deve essere lungo al massimo 50 caratteri..
        /// </summary>
        public static string ColorLength {
            get {
                return ResourceManager.GetString("ColorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been confirmed successfully..
        /// </summary>
        public static string ConfirmEmailSuccess {
            get {
                return ResourceManager.GetString("ConfirmEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC è incompleto..
        /// </summary>
        public static string CVC {
            get {
                return ResourceManager.GetString("CVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descrizione è obbligatoria..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descrizione deve contenere un massimo di 500 caratteri..
        /// </summary>
        public static string DescriptionLength {
            get {
                return ResourceManager.GetString("DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tuo account e-mail è stato confermato una volta..
        /// </summary>
        public static string EmailConfirmedOnce {
            get {
                return ResourceManager.GetString("EmailConfirmedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;e-mail è obbligatoria..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di scadenza è incompleta..
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il tuo nome completo (Nome/spazio/Cognome)..
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il sesso è obbligatorio..
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome dell&apos;immagine non può essere lungo più di 500 caratteri..
        /// </summary>
        public static string ImagePathLength {
            get {
                return ResourceManager.GetString("ImagePathLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email non valido..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativo di accesso non valido..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password non valida..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile caricare l&apos;utente con ID userId!.
        /// </summary>
        public static string LoadUserError {
            get {
                return ResourceManager.GetString("LoadUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi confermare la tua email per poter accedere..
        /// </summary>
        public static string MustConfirmEmailError {
            get {
                return ResourceManager.GetString("MustConfirmEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome deve essere lungo almeno 2 e massimo 100 caratteri..
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il campo nome  è obbligatorio ..
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password deve contenere almeno 6 caratteri e una lunghezza massima di 100 caratteri..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password e la password di conferma non corrispondono..
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password  è obbligatoria..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il prezzo è obbligatorio..
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezzo non valido. Punti decimali massimi: 2.
        /// </summary>
        public static string PriceFormat {
            get {
                return ResourceManager.GetString("PriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezzo non valido. Lunghezza massima: 10..
        /// </summary>
        public static string PriceLength {
            get {
                return ResourceManager.GetString("PriceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È stata inviata un&apos;e-mail a questo indirizzo e-mail. Controlla il tuo indirizzo email..
        /// </summary>
        public static string ResetPasswordEmailSent {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tua password è stata reimpostata con successo..
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome deve essere lungo almeno 2 e massimo 50 caratteri..
        /// </summary>
        public static string SubjectNameLength {
            get {
                return ResourceManager.GetString("SubjectNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il cognome deve essere di almeno 2 e massimo 100 caratteri..
        /// </summary>
        public static string SurnameLength {
            get {
                return ResourceManager.GetString("SurnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il campo Cognome è obbligatorio..
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore. Per favore, riprova a confermare la tua email!.
        /// </summary>
        public static string TryAgainEmailConfirmation {
            get {
                return ResourceManager.GetString("TryAgainEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore. Per favore, riprova..
        /// </summary>
        public static string TryAgainError {
            get {
                return ResourceManager.GetString("TryAgainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente creato con successo. Controlla la tua email per la verifica..
        /// </summary>
        public static string UserCreationSucces {
            get {
                return ResourceManager.GetString("UserCreationSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore. Utente non trovato..
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore. L&apos;utente non è registrato o non ha confermato l&apos;e-mail..
        /// </summary>
        public static string UserNotRegistredOrEmailNotConfirmed {
            get {
                return ResourceManager.GetString("UserNotRegistredOrEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente con e-mail E-mail non trovata..
        /// </summary>
        public static string UserWithEmailNotFound {
            get {
                return ResourceManager.GetString("UserWithEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi fornire un indirizzo email valido..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimo otto caratteri, almeno una lettera maiuscola, una lettera minuscola e un numero..
        /// </summary>
        public static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
    }
}
